# Generated by Django 3.0.8 on 2020-08-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='listing_bids', to='auctions.Bid'),
        ),
    ]
